Repository AY2021S2-CS2103-T14-2/tp, pull requests merged in 2021-04, with the labels that each got.

#184 Marcus PED bug fix
  docs/UserGuide.md
  docs/team/marcusleeeugene.md
  src/main/java/fooddiary/model/entry/Price.java
  src/main/java/fooddiary/model/entry/Rating.java
  src/main/java/fooddiary/model/entry/Review.java
  src/main/java/fooddiary/ui/EntryCard.java
  src/main/java/fooddiary/ui/ReviseWindow.java
Labels: priority.High

#186 Fix issue #152
  docs/UserGuide.md
Labels: type.Bug

#189 Dinesh ped bugfixes
  docs/UserGuide.md
  src/main/java/fooddiary/commons/core/Messages.java
  src/main/java/fooddiary/logic/commands/AddCommand.java
  src/main/java/fooddiary/logic/commands/AddOnCommand.java
  src/main/java/fooddiary/logic/commands/DeleteCommand.java
  src/main/java/fooddiary/logic/commands/EditCommand.java
  src/main/java/fooddiary/logic/commands/ReviseCommand.java
  src/main/java/fooddiary/logic/commands/ViewCommand.java
  src/main/java/fooddiary/logic/parser/AddOnCommandParser.java
  src/main/java/fooddiary/logic/parser/DeleteCommandParser.java
  src/main/java/fooddiary/logic/parser/EditCommandParser.java
  src/main/java/fooddiary/logic/parser/ParserUtil.java
  src/main/java/fooddiary/logic/parser/ReviseCommandParser.java
  src/main/java/fooddiary/logic/parser/ViewCommandParser.java
  src/test/java/fooddiary/logic/LogicManagerTest.java
  src/test/java/fooddiary/logic/commands/AddCommandIntegrationTest.java
  src/test/java/fooddiary/logic/commands/AddOnCommandTest.java
  src/test/java/fooddiary/logic/commands/ClearCommandTest.java
  src/test/java/fooddiary/logic/commands/CommandTestUtil.java
  src/test/java/fooddiary/logic/commands/DeleteCommandTest.java
  src/test/java/fooddiary/logic/commands/EditCommandTest.java
  src/test/java/fooddiary/logic/commands/FindAllCommandTest.java
  src/test/java/fooddiary/logic/commands/FindCommandTest.java
  src/test/java/fooddiary/logic/commands/ListCommandTest.java
  src/test/java/fooddiary/logic/commands/ReviseCommandTest.java
  src/test/java/fooddiary/logic/commands/ViewCommandTest.java
  src/test/java/fooddiary/logic/parser/AddOnCommandParserTest.java
  src/test/java/fooddiary/logic/parser/DeleteCommandParserTest.java
  src/test/java/fooddiary/logic/parser/EditCommandParserTest.java
  src/test/java/fooddiary/logic/parser/ParserUtilTest.java
  src/test/java/fooddiary/logic/parser/ReviseCommandParserTest.java
  src/test/java/fooddiary/logic/parser/ViewCommandParserTest.java
  src/test/java/fooddiary/model/FoodDiaryTest.java
  src/test/java/fooddiary/storage/JsonFoodDiaryStorageTest.java
  src/test/java/fooddiary/storage/JsonSerializableFoodDiaryTest.java
  src/test/java/fooddiary/storage/StorageManagerTest.java
  src/test/java/fooddiary/testutil/TypicalEntries.java
  src/test/java/fooddiary/testutil/TypicalIndexes.java
Labels: priority.High

#193 Dinesh ppp draft
  docs/team/dineshmagesvaran.md
Labels: priority.Medium

#210 Dinesh update dg 2
  docs/DeveloperGuide.md
  docs/images/FindAllSequenceDiagram.PNG
  docs/images/FindAllSequenceDiagram.png
  docs/images/Storage.png
  docs/team/dineshmagesvaran.md
Labels: priority.High
