Repository AY2021S2-CS2103-T14-2/tp, pull requests merged in 2021-03, with the labels that each got.

#46 UG: Update the file name of UI Mockup picture
  docs/UserGuide.md
Labels: type.Bug

#53 Search feature
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium

#52 Add review of food experience of a Restaurant
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Review.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/ReviewTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#64 Update sample data for Demo
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task

#65 Update UG with review and rating feature merge conflicts
  docs/UserGuide.md
Labels: type.Bug

#66 Refactor AddressBook in Index.md to FoodDiary and minor fixes
  docs/index.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug

#76 View feature refinement
  build.gradle
  docs/DeveloperGuide.md
  docs/images/ViewActivityDiagram.png
  docs/images/ViewSequenceDiagram.png
  src/main/java/fooddiary/logic/commands/ViewCommand.java
  src/main/java/fooddiary/logic/parser/ViewCommandParser.java
  src/main/java/fooddiary/ui/MainWindow.java
  src/main/resources/view/ViewWindow.fxml
  src/test/java/fooddiary/logic/parser/ViewCommandParserTest.java
Labels: priority.Medium

#75 Addon multiple reviews
  docs/DeveloperGuide.md
  src/main/java/fooddiary/logic/commands/AddOnCommand.java
  src/main/java/fooddiary/logic/commands/EditCommand.java
  src/main/java/fooddiary/logic/parser/AddOnCommandParser.java
  src/main/java/fooddiary/logic/parser/FoodDiaryParser.java
  src/main/java/fooddiary/model/entry/Review.java
  src/main/java/fooddiary/ui/EntryCard.java
  src/test/java/fooddiary/logic/parser/AddOnCommandParserTest.java
  src/test/java/fooddiary/testutil/AddOnEntryDescriptorBuilder.java
Labels: priority.Medium

#77 New Price Feature & some refactoring
  build.gradle
  src/main/java/fooddiary/logic/commands/AddCommand.java
  src/main/java/fooddiary/logic/commands/EditCommand.java
  src/main/java/fooddiary/logic/commands/FindCommand.java
  src/main/java/fooddiary/logic/parser/AddCommandParser.java
  src/main/java/fooddiary/logic/parser/CliSyntax.java
  src/main/java/fooddiary/logic/parser/EditCommandParser.java
  src/main/java/fooddiary/logic/parser/ParserUtil.java
  src/main/java/fooddiary/model/entry/Entry.java
  src/main/java/fooddiary/model/entry/NameContainsAllKeywordsPredicate.java
  src/main/java/fooddiary/model/entry/NameContainsKeywordsPredicate.java
  src/main/java/fooddiary/model/entry/Price.java
  src/main/java/fooddiary/model/entry/Rating.java
  src/main/java/fooddiary/model/util/SampleDataUtil.java
  src/main/java/fooddiary/storage/JsonAdaptedEntry.java
  src/main/java/fooddiary/ui/EntryCard.java
  src/main/resources/view/EntryListCard.fxml
  src/test/data/JsonFoodDiaryStorageTest/invalidAndValidEntryFoodDiary.json
  src/test/data/JsonFoodDiaryStorageTest/invalidEntryFoodDiary.json
  src/test/data/JsonSerializableFoodDiaryTest/duplicateEntryFoodDiary.json
  src/test/data/JsonSerializableFoodDiaryTest/invalidEntryFoodDiary.json
  src/test/data/JsonSerializableFoodDiaryTest/typicalEntriesFoodDiary.json
  src/test/java/fooddiary/logic/LogicManagerTest.java
  src/test/java/fooddiary/logic/commands/AddCommandTest.java
  src/test/java/fooddiary/logic/commands/CommandTestUtil.java
  src/test/java/fooddiary/logic/commands/EditCommandTest.java
  src/test/java/fooddiary/logic/commands/EditEntryDescriptorTest.java
  src/test/java/fooddiary/logic/commands/FindAllCommandTest.java
  src/test/java/fooddiary/logic/commands/FindCommandTest.java
  src/test/java/fooddiary/logic/parser/AddCommandParserTest.java
  src/test/java/fooddiary/logic/parser/EditCommandParserTest.java
  src/test/java/fooddiary/logic/parser/FindAllCommandParserTest.java
  src/test/java/fooddiary/logic/parser/FindCommandParserTest.java
  src/test/java/fooddiary/logic/parser/FoodDiaryParserTest.java
  src/test/java/fooddiary/logic/parser/ParserUtilTest.java
  src/test/java/fooddiary/model/FoodDiaryTest.java
  src/test/java/fooddiary/model/ModelManagerTest.java
  src/test/java/fooddiary/model/entry/EntryTest.java
  src/test/java/fooddiary/model/entry/NameContainsAllKeywordsPredicateTest.java
  src/test/java/fooddiary/model/entry/NameContainsKeywordsPredicateTest.java
  src/test/java/fooddiary/model/entry/NameTest.java
  src/test/java/fooddiary/model/entry/PriceTest.java
  src/test/java/fooddiary/model/entry/ReviewTest.java
  src/test/java/fooddiary/model/entry/UniqueEntryListTest.java
  src/test/java/fooddiary/storage/JsonAdaptedEntryTest.java
  src/test/java/fooddiary/storage/JsonFoodDiaryStorageTest.java
  src/test/java/fooddiary/storage/JsonSerializableFoodDiaryTest.java
  src/test/java/fooddiary/storage/JsonUserPrefsStorageTest.java
  src/test/java/fooddiary/testutil/EditEntryDescriptorBuilder.java
  src/test/java/fooddiary/testutil/EntryBuilder.java
  src/test/java/fooddiary/testutil/EntryUtil.java
  src/test/java/fooddiary/testutil/TypicalEntries.java
Labels: priority.Medium

#86 81 addon review save bug
  src/main/java/fooddiary/logic/LogicManager.java
  src/main/java/fooddiary/logic/commands/AddOnCommand.java
  src/main/java/fooddiary/logic/commands/EditCommand.java
  src/main/java/fooddiary/logic/commands/ViewCommand.java
  src/main/java/fooddiary/logic/parser/AddCommandParser.java
  src/main/java/fooddiary/logic/parser/AddOnCommandParser.java
  src/main/java/fooddiary/logic/parser/ArgumentMultimap.java
  src/main/java/fooddiary/logic/parser/EditCommandParser.java
  src/main/java/fooddiary/logic/parser/ParserUtil.java
  src/main/java/fooddiary/model/entry/Entry.java
  src/main/java/fooddiary/model/entry/Review.java
  src/main/java/fooddiary/model/util/SampleDataUtil.java
  src/main/java/fooddiary/storage/JsonAdaptedEntry.java
  src/main/java/fooddiary/storage/JsonAdaptedReview.java
  src/main/java/fooddiary/ui/EntryCard.java
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/ViewWindow.fxml
  src/test/data/JsonFoodDiaryStorageTest/invalidAndValidEntryFoodDiary.json
  src/test/data/JsonFoodDiaryStorageTest/invalidEntryFoodDiary.json
  src/test/data/JsonSerializableFoodDiaryTest/duplicateEntryFoodDiary.json
  src/test/data/JsonSerializableFoodDiaryTest/invalidEntryFoodDiary.json
  src/test/data/JsonSerializableFoodDiaryTest/typicalEntriesFoodDiary.json
  src/test/java/fooddiary/logic/commands/CommandTestUtil.java
  src/test/java/fooddiary/logic/commands/EditEntryDescriptorTest.java
  src/test/java/fooddiary/logic/parser/AddCommandParserTest.java
  src/test/java/fooddiary/logic/parser/EditCommandParserTest.java
  src/test/java/fooddiary/model/entry/EntryTest.java
  src/test/java/fooddiary/model/entry/NameContainsAllKeywordsPredicateTest.java
  src/test/java/fooddiary/model/entry/NameContainsKeywordsPredicateTest.java
  src/test/java/fooddiary/storage/JsonAdaptedEntryTest.java
  src/test/java/fooddiary/testutil/AddOnEntryDescriptorBuilder.java
  src/test/java/fooddiary/testutil/EditEntryDescriptorBuilder.java
  src/test/java/fooddiary/testutil/EntryBuilder.java
  src/test/java/fooddiary/testutil/EntryUtil.java
  src/test/java/fooddiary/testutil/TypicalEntries.java
Labels: type.Bug

#93 Fix View Command for new tags implementation
  src/main/java/fooddiary/ui/EntryCard.java
  src/main/java/fooddiary/ui/MainWindow.java
  src/main/java/fooddiary/ui/ViewWindow.java
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewWindow.fxml
Labels: priority.Medium, type.Task

#95 Improved price feature
  src/main/java/fooddiary/model/entry/Price.java
  src/main/java/fooddiary/model/entry/Rating.java
  src/test/java/fooddiary/model/entry/PriceTest.java
Labels: priority.Medium

#97 Feature addon price
  docs/UserGuide.md
  src/main/java/fooddiary/logic/commands/AddOnCommand.java
  src/main/java/fooddiary/logic/parser/AddOnCommandParser.java
  src/main/java/fooddiary/ui/EntryCard.java
  src/test/java/fooddiary/logic/commands/CommandTestUtil.java
  src/test/java/fooddiary/testutil/AddOnEntryDescriptorBuilder.java
Labels: priority.Medium

#100 Revise feature minor fix
  src/main/java/fooddiary/ui/EntryCard.java
  src/main/java/fooddiary/ui/MainWindow.java
  src/main/java/fooddiary/ui/ReviseWindow.java
  src/main/java/fooddiary/ui/ViewWindow.java
  src/main/resources/view/ViewWindow.fxml
  src/test/java/fooddiary/commons/util/JsonUtilTest.java
Labels: priority.Medium

#103 Revise feature v1.3b ready
  src/main/java/fooddiary/ui/HelpWindow.java
  src/main/java/fooddiary/ui/MainWindow.java
  src/main/java/fooddiary/ui/ReviseWindow.java
  src/main/java/fooddiary/ui/ViewWindow.java
  src/main/resources/view/ReviseWindow.fxml
Labels: priority.Medium

#110 Dinesh update UG 2
  docs/UserGuide.md
  src/main/java/fooddiary/model/entry/NameContainsAllKeywordsPredicate.java
  src/main/java/fooddiary/model/entry/NameContainsKeywordsPredicate.java
Labels: priority.High

#113 Marcus v1.3b ug
  docs/UserGuide.md
  docs/images/ViewWindowUi.png
  src/main/java/fooddiary/ui/ReviseWindow.java
Labels: priority.Medium

#117 Final v1.3b fix
  src/main/java/fooddiary/MainApp.java
  src/main/java/fooddiary/ui/HelpWindow.java
Labels: priority.Medium
